# -*- coding: utf-8 -*-
"""todo_list.ipynb의 사본

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UyaiVk0ecDo3AqmVnanDzUQR9z7U8nLJ
"""

class ToDoList:
    def __init__(self):
        self.tasks = []

    def add_task(self, task):
        self.tasks.append({'description': task, 'completed': False})

    def complete_task(self, index):
        if index < 0 or index >= len(self.tasks):
            print("Invalid task number.")
        else:
            self.tasks[index]['completed'] = True

    def delete_task(self, index):
        if index < 0 or index >= len(self.tasks):
            print("Invalid task number.")
        else:
            del self.tasks[index]

    def list_tasks(self):
        if not self.tasks:
            print("No tasks to show.")
            return
        for i, task in enumerate(self.tasks, 1):
            status = 'Done' if task['completed'] else 'Not Done'
            print(f"{i}. {task['description']} - {status}")

def main_menu():
    to_do_list = ToDoList()
    while True:
        print("""
        To Do List Application
        ----------------------
        1. List all tasks
        2. Add a new task
        3. Mark task as completed
        4. Delete a task
        5. Exit
        """)
        choice = input("Enter your choice: ")
        if choice == '1':
            to_do_list.list_tasks()
        elif choice == '2':
            task = input("Enter the task description: ")
            to_do_list.add_task(task)
        elif choice == '3':
            to_do_list.list_tasks()
            if to_do_list.tasks:
                task_index = int(input("Enter the number of the task to mark as completed: ")) - 1
                to_do_list.complete_task(task_index)
        elif choice == '4':
            to_do_list.list_tasks()
            if to_do_list.tasks:
                task_index = int(input("Enter the number of the task to delete: ")) - 1
                to_do_list.delete_task(task_index)
        elif choice == '5':
            print("Exiting the application.")
            break
        else:
            print("Invalid choice. Please try again.")

if __name__ == "__main__":
    main_menu()